### ISSUE TITLE
Increase size of boxes

### ISSUE THREAD

**Issue by computangit** [computangit/molestreet-finpay#4]
To match mockup, increase the size of the boxes: 

Christopher: 355px
John: 330px
Lauren: 365px
Jennifer: 365px

and make text 1 pixel bigger to match the box. 

Recommendation: Add pixels on top and bottom but mostly on bottom.
--
EL

**URL tested:** https://www.finpay.net/about-us/

Open [URL](https://live.browserstack.com/#os=OS+X&os_version=Catalina&browser=Safari&browser_version=13.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.finpay.net%2Fabout-us%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.finpay.net/about-us/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Safari 13.0 |
| Operating System | OS X Catalina |
| Resolution | 1366x642 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d61e09d7b7331546eb0f0169b557ab038f907d01/maccat_safari_13.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/d61e09d7b7331546eb0f0169b557ab038f907d01/maccat_safari_13.0.jpg)

**[Click here](https://live.browserstack.com/#os=OS+X&os_version=Catalina&browser=Safari&browser_version=13.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.finpay.net%2Fabout-us%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.finpay.net/about-us/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by computangit** [comment]
In design there is using enter after a text if we add there </br> then it match with design but we use this generic box and use same styling if i increase font size its not match with design.

**Comment by computangit** [comment]
Fixed
Sajjad Ali Khan.

**Comment by HumanEligreg** [comment]
Closed issue
--
Eligreg

**Comment by computangit** [comment]
Closed
--
Eligreg
